-- MySQL Script generated by MySQL Workbench
-- Fri Oct 28 21:20:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mifactura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mifactura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mifactura` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `mifactura` ;

-- -----------------------------------------------------
-- Table `mifactura`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mifactura`.`Usuario` (
  `Codigo` NVARCHAR(20) NOT NULL,
  `Nombre` NVARCHAR(50) NOT NULL,
  `Clave` NVARCHAR(100) NOT NULL,
  `Correo` NVARCHAR(45) NULL,
  `ROL` NVARCHAR(20) NOT NULL,
  `EstaActivo` TINYINT NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mifactura`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mifactura`.`Producto` (
  `Codigo` INT NOT NULL,
  `Descripción` NVARCHAR(50) NOT NULL,
  `Existencia` INT NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
